### ISSUE TITLE
sequelize breaks with honeycomb enabled

### ISSUE THREAD

**Issue by alex1x** [honeycombio/beeline-nodejs#102]
I get this error when running sequelize queries:

```
Executing (default): SELECT `id`, `title`, `description`, `price`, `imageURL`, `createdAt`, `updatedAt` FROM `products` AS `product`;
TypeError: Cannot read property 'setMaxListeners' of undefined
    at Utils.Promise (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\dialects\mysql\query.js:77:58)
    at Promise._execute (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:79:10)
    at Query.run (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\dialects\mysql\query.js:57:12)
    at Promise.try.then.connection (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\sequelize.js:558:20)
    at C:\Users\Alex\WebstormProjects\untitled\node_modules\honeycomb-beeline\lib\async_tracker.js:47:19
    at tryCatcher (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (timers.js:632:19)
TypeError: Cannot read property 'setMaxListeners' of undefined
    at Utils.Promise (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\dialects\mysql\query.js:77:58)
    at Promise._execute (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:79:10)
    at Query.run (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\dialects\mysql\query.js:57:12)
    at Promise.try.then.connection (C:\Users\Alex\WebstormProjects\untitled\node_modules\sequelize\lib\sequelize.js:558:20)
    at C:\Users\Alex\WebstormProjects\untitled\node_modules\honeycomb-beeline\lib\async_tracker.js:47:19
    at tryCatcher (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Alex\WebstormProjects\untitled\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (timers.js:632:19)
```

Node version is `v11.0.0`.

I prepared this snippet for you to illustrate the issue:

```
// require("honeycomb-beeline")({
//   writeKey: process.env.HONEYCOMB_INGEST_KEY
//   /* ... additional optional configuration ... */
// });

const express = require("express");
const app = express();

const Sequelize = require("sequelize");
const sequelize = new Sequelize(
  "honeycomb-repro",
  process.env.LOCAL_MYSQL_USER,
  process.env.LOCAL_MYSQL_PASSWORD,
  {
    dialect: "mysql",
    host: "localhost"
  }
);

const Item = sequelize.define("item", {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    allowNull: false,
    primaryKey: true
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false
  }
});

sequelize
  .sync()
  .then(data => {
    return Item.create({
      title: "hello honeycomb"
    });
  })
  .then(data => {
    return Item.findById(data.dataValues.id);
  })
  .then(data => {
    console.log(data.dataValues);
    app.use("/", (req, res, next) => {
      Item.findAll()
        .then(items => {
          res.send(items);
        })
        .catch(err => console.log(err));
    });
    app.listen(8080);
  });
```

If you run this (I run it against a local mysql instance) you should see it fail with above error. If you uncomment the first 4 lines and run again you'll see it working.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
