### ISSUE TITLE
"we lost our tracking" report

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [honeycombio/beeline-nodejs#103]
Here's the stack trace (node 8.14.0):
```
dev_1     | 2018-12-12T01:10:37.360Z honeycomb-beeline:express -------------------
dev_1     |     honeycomb-beeline error: we lost our tracking somewhere in the middleware registered:
dev_1     |     at Function.<anonymous> (/app/node_modules/express/lib/application.js:220:21)
dev_1     |     at Array.forEach (<anonymous>)
dev_1     |     at Function.use (/app/node_modules/express/lib/application.js:217:7)
dev_1     |     at Object.<anonymous> (/app/app.js:115:5)
dev_1     |     at Module._compile (module.js:653:30)
dev_1     |     at Object.Module._extensions..js (module.js:664:10)
dev_1     |     at Module.load (module.js:566:32)
dev_1     |     at tryModuleLoad (module.js:506:12)
dev_1     |     at Function.Module._load (module.js:498:3)
dev_1     |     at Function._load (/app/node_modules/honeycomb-beeline/lib/instrumentation.js:152:28)
dev_1     |     at Module.require (module.js:597:17)
dev_1     |     at require (internal/module.js:11:18)
dev_1     |     at Object.<anonymous> (/app/index.js:8:11)
dev_1     |     at Module._compile (module.js:653:30)
dev_1     |     at Object.Module._extensions..js (module.js:664:10)
dev_1     |     at Module.load (module.js:566:32)
dev_1     |     at tryModuleLoad (module.js:506:12)
dev_1     |     at Function.Module._load (module.js:498:3)
dev_1     |     at Function.Module.runMain (module.js:694:10)
dev_1     |     at startup (bootstrap_node.js:204:16)
dev_1     |     at bootstrap_node.js:625:3
dev_1     |     please paste this message (everything between the "----" lines) into an issue
dev_1     |     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
dev_1     |     out any application stack frames if you'd rather not share those
dev_1     |     Error
dev_1     |     at LibhoneyEventAPI.askForIssue (/app/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
dev_1     |     at Object._askForIssue (/app/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
dev_1     |     at wrappedNext (/app/node_modules/honeycomb-beeline/lib/instrumentation/express.js:125:15)
dev_1     |     at /app/node_modules/body-parser/lib/read.js:130:5
dev_1     |     at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
dev_1     |     at done (/app/node_modules/raw-body/index.js:213:7)
dev_1     |     at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
dev_1     |     at emitNone (events.js:106:13)
dev_1     |     at IncomingMessage.emit (events.js:208:7)
dev_1     |     at endReadableNT (_stream_readable.js:1064:12)
dev_1     |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
dev_1     |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
dev_1     |
dev_1     |     -------------------
```

Please let me know if I can provide any other info!

**Comment by toshok** [comment]
hmm, is this still happening for you?  That stack is unfortunately not particularly useful.  What middleware is being registered at:

```
dev_1     |     at Object.<anonymous> (/app/app.js:115:5)
```

?

**Comment by onlytracks** [comment]
I have seen something similar only when I have the debug output turned on when receiving a post request with a json body.  In our case I am able to narrow it down to something with the `body-parser` module.  I can reproduce it with something like the below:
```
// Node 10.15.0
// honeycomb-beeline 1.3.1
// body-parser 1.81.3
// express 4.16.4
// helmet 3.15.0

process.env.DEBUG = "honeycomb-beeline:*"  // <-- only shows up when this is on

const honey = require("honeycomb-beeline")
honey({
  writeKey   : process.env.HONEY_WRITEKEY,
  dataset    : process.env.HONEY_DATASET,
  serviceName: process.env.HONEY_SERVICENAME
})
const bodyParser = require("body-parser")
const express = require("express")
const helmet = require("helmet")

const app = express()
app.use(helmet.hidePoweredBy())
app.use(bodyParser.json())     // <-- note bodyParser is the second app.use entry
app.use(function(req, res) {
  res.send("Hello, World!")
})
app.listen(3000)
```

Then issue a post request that contains a json body:
```
curl -X POST -H "Content-Type: application/json" -d '{"test":"content"}' http://localhost:3000
```

However, if you move the `app.use(bodyParser.json())` to be the first `app.use`, the error goes away.  Example:
```
// ...
const app = express()
app.use(bodyParser.json())    // <-- note bodyParser is the first app.use entry
app.use(helmet.hidePoweredBy())
app.use(function(req, res) {
  res.send("Hello, World!")
})
// ...
```

Also, I noticed if the post body is empty, there is no error.
```
curl -X POST -H "Content-Type: application/json" http://localhost:3000
```

**Comment by danyelf** [comment]
Thanks! It looks like the issue is that the Beeline doesn't manage to pass the trace context into the new parser that the middleware generates. We have a command, bindFunctionToTrace which is meant to help with this. 

In this case: another user reported that they managed to get there by adding function `bind(req, res, next) {
jsonParser(req, res, beeline.bindFunctionToTrace(next));}`, in place of jsonParser

**Comment by JamieDanielson** [comment]
We’re going to close this for now as there has been no recent activity and it appears a solution was provided in an earlier comment. Feel free to request a re-open if it’s still relevant.
