### ISSUE TITLE
Error finishing spans in https requests

### ISSUE THREAD

**Issue by MihailDraghici** [honeycombio/beeline-nodejs#106]
**Node version: 8.12.0**

**Code:**
```
const beeline = require('honeycomb-beeline')({
  writeKey: 'WRITE_KEY',
  dataset: 'DATASET',
});

require('http');
require('https');
const request = require('request-promise-native');

const trace = beeline.startTrace({
  task: 'http request',
});

request({
  method: 'GET',
  url: 'https://www.google.ro',
}).then(() => {
  beeline.finishTrace(trace);
});
```

**Error:**
```
honeycomb-beeline:event -------------------
  honeycomb-beeline:event     honeycomb-beeline error: no payload for event we're trying to finish (stack is empty).
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:event     out any application stack frames if you'd rather not share those
  honeycomb-beeline:event     Error
  honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (.../node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
  honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (.../node_modules/honeycomb-beeline/lib/api/libhoney.js:149:12)
  honeycomb-beeline:event     at Object.finishSpan (.../node_modules/honeycomb-beeline/lib/api/index.js:67:20)
  honeycomb-beeline:event     at ClientRequest.wrapped_cb (.../node_modules/honeycomb-beeline/lib/instrumentation/https.js:49:17)
  honeycomb-beeline:event     at emitOne (events.js:121:20)
  honeycomb-beeline:event     at ClientRequest.emit (events.js:211:7)
  honeycomb-beeline:event     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
  honeycomb-beeline:event     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
  honeycomb-beeline:event     at TLSSocket.socketOnData (_http_client.js:440:20)
  honeycomb-beeline:event     at emitOne (events.js:116:13)
  honeycomb-beeline:event     current request context:
  honeycomb-beeline:event     ------------------- +0ms
```

**Comment by toshok** [comment]
betting this has something to do with the fact that node 8's `https` calls into `http`.

**Comment by toshok** [comment]
yeah.  so it looks like it's due to our https instrumentation calling into the http instrumentation, along with the way async spans are created.  fix coming
