### ISSUE TITLE
Error: `no context in finishSpan` with `startSpan` and `startAsyncSpan`

### ISSUE THREAD

**Issue by jceipek** [honeycombio/beeline-nodejs#120]
# Using `startAsyncSpan`:
```
honeycomb-beeline:event -------------------
honeycomb-beeline:event     honeycomb-beeline error: no context in finishSpan.
honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
honeycomb-beeline:event     out any application stack frames if you'd rather not share those
honeycomb-beeline:event     Error
honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:143:12)
honeycomb-beeline:event     at Function.finishSpan (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/index.js:68:20)
honeycomb-beeline:event     at Command._client.srem [as callback] (REDACTED_PATH/dist/server/database.js:217:30)
honeycomb-beeline:event     at normal_reply (REDACTED_PATH/node_modules/redis/index.js:726:21)
honeycomb-beeline:event     at RedisClient.return_reply (REDACTED_PATH/node_modules/redis/index.js:824:9)
honeycomb-beeline:event     at JavascriptRedisParser.returnReply (REDACTED_PATH/node_modules/redis/index.js:192:18)
honeycomb-beeline:event     at JavascriptRedisParser.execute (REDACTED_PATH/node_modules/redis-parser/lib/parser.js:574:12)
honeycomb-beeline:event     at Socket.<anonymous> (REDACTED_PATH/node_modules/redis/index.js:274:27)
honeycomb-beeline:event     at Socket.emit (events.js:188:13)
honeycomb-beeline:event
honeycomb-beeline:event     ------------------- +17ms
honeycomb-beeline:event finishing span {"meta.local_hostname":"REDACTED_HOSTNAME","service_name":null,"meta.type":"express","meta.package_version":"4.16.4","name":"request","trace.trace_id_source":null,"request.host":"REDACTED_HOST","request.base_url":"","request.original_url":"REDACTED_URL","request.remote_addr":"::ffff:127.0.0.1","request.secure":false,"request.method":"POST","request.route":null,"request.scheme":"http","request.path":"REDACTED_PATH","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"4d193536-653c-4c60-ab1a-764910538afe","trace.span_id":"45b6bae3-1e53-44ed-84ed-f06db6ab1f53","duration_ms":14.431615,"app.r1":"REDACTED_R1","app.r2":"REDACTED_FIELD","response.status_code":"200","meta.instrumentations":["express","http","https"],"meta.instrumentation_count":3,"meta.beeline_version":"1.3.1","meta.node_version":"v11.6.0"} +2ms
```

## Source:

```
function foo(redactedField) {
    return new Promise((resolve, reject) => {
        const redactedKey = 'REDACTED_KEY';
        _beeline.startAsyncSpan({
            task: 'foo',
            'redis.cmd': 'srem',
            'redis.key': redactedKey,
            'redis.field': redactedField
        }, (span) => {
            console.log(`TRACE ACTIVE? ${_beeline.traceActive()}`); // returns true
            _client.srem(redactedKey, redactedField, (err, reply) => {
                if (err) {
                    _beeline.customContext.add("redis.err", err.toString());
                    _beeline.finishSpan(span);
                    reject(err);
                }
                else {
                    _beeline.customContext.add("redis.reply", reply);
                    _beeline.finishSpan(span);
                    resolve(reply);
                }
            });
        });
    });
}

async function onBar(redactedField) {
    return await foo(redactedField);
}

myExpressRouter.post('/redactedPath', middleware1, middleware2, middleware3, (req, res) => {
    const r1 = req.body.redactedField;
    const r2 = req.body.redactedField2;
    beeline.customContext.add('r1', r1);
    beeline.customContext.add('r2', r2);
    db.onBar(r1).then((barResult) => {
        res.json({ "REDACTED_PAYLOAD": true });
    }).catch((reason) => {
        res.json({ "REDACTED_PAYLOAD": false });
    });
});
```

# Using `startSpan`:

```
honeycomb-beeline:event -------------------
honeycomb-beeline:event     honeycomb-beeline error: no context in finishSpan.
honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
honeycomb-beeline:event     out any application stack frames if you'd rather not share those
honeycomb-beeline:event     Error
honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:143:12)
honeycomb-beeline:event     at Function.finishSpan (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/index.js:68:20)
honeycomb-beeline:event     at Command._client.srem [as callback] (REDACTED_PATH/dist/server/database.js:198:26)
honeycomb-beeline:event     at normal_reply (REDACTED_PATH/node_modules/redis/index.js:726:21)
honeycomb-beeline:event     at RedisClient.return_reply (REDACTED_PATH/node_modules/redis/index.js:824:9)
honeycomb-beeline:event     at JavascriptRedisParser.returnReply (REDACTED_PATH/node_modules/redis/index.js:192:18)
honeycomb-beeline:event     at JavascriptRedisParser.execute (REDACTED_PATH/node_modules/redis-parser/lib/parser.js:574:12)
honeycomb-beeline:event     at Socket.<anonymous> (REDACTED_PATH/node_modules/redis/index.js:274:27)
honeycomb-beeline:event     at Socket.emit (events.js:188:13)
honeycomb-beeline:event
honeycomb-beeline:event     ------------------- +28ms
honeycomb-beeline:event -------------------
honeycomb-beeline:event     honeycomb-beeline error: finishing an event with unfinished nested events. almost certainly not what we want.
honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
honeycomb-beeline:event     out any application stack frames if you'd rather not share those
honeycomb-beeline:event     Error
honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:159:12)
honeycomb-beeline:event     at LibhoneyEventAPI.finishTrace (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/libhoney.js:87:10)
honeycomb-beeline:event     at Object.finishTrace (REDACTED_PATH/node_modules/honeycomb-beeline/lib/api/index.js:52:20)
honeycomb-beeline:event     at api.bindFunctionToTrace (REDACTED_PATH/node_modules/honeycomb-beeline/lib/instrumentation/express.js:233:9)
honeycomb-beeline:event     at REDACTED_PATH/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
honeycomb-beeline:event     at ServerResponse.<anonymous> (REDACTED_PATH/node_modules/honeycomb-beeline/lib/instrumentation/express.js:237:12)
honeycomb-beeline:event     at ServerResponse.writeHead (REDACTED_PATH/node_modules/on-headers/index.js:46:16)
honeycomb-beeline:event     at ServerResponse._implicitHeader (_http_server.js:199:8)
honeycomb-beeline:event     at write_ (_http_outgoing.js:597:9)
honeycomb-beeline:event     current request context:
honeycomb-beeline:event 0: {"meta.type":"express","meta.package_version":"4.16.4","name":"request","request.host":"REDACTED_HOST","request.base_url":"","request.original_url":"REDACTED_URL","request.remote_addr":"::ffff:127.0.0.1","request.secure":false,"request.method":"POST","request.scheme":"http","request.path":"REDACTED_PATH","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"4aeba4a1-6f0e-4c0a-b097-1a7ed4a3d031","trace.span_id":"c0a80028-18f1-47f1-b17c-37049ca3537d","startTime":1548368134325,"startTimeHR":[352623,786902963]}
honeycomb-beeline:event 1: {"task":"removeRoomFromPending","redis.cmd":"srem","redis.key":"REDACTED_KEY","redis.field":"REDACTED_FIELD","trace.trace_id":"4aeba4a1-6f0e-4c0a-b097-1a7ed4a3d031","trace.span_id":"9ff37d29-3d47-46b5-840f-d2c2c1a361aa","startTime":1548368134349,"startTimeHR":[352623,810509042],"trace.parent_id":"c0a80028-18f1-47f1-b17c-37049ca3537d"}
honeycomb-beeline:event     ------------------- +1ms
honeycomb-beeline:event finishing span {"meta.local_hostname":"REDACTED_HOSTNAME","service_name":null,"meta.type":"express","meta.package_version":"4.16.4","name":"request","trace.trace_id_source":null,"request.host":"REDACTED_HOST","request.base_url":"","request.original_url":"REDACTED_URL","request.remote_addr":"::ffff:127.0.0.1","request.secure":false,"request.method":"POST","request.route":null,"request.scheme":"http","request.path":"REDACTED_PATH","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"4aeba4a1-6f0e-4c0a-b097-1a7ed4a3d031","trace.span_id":"c0a80028-18f1-47f1-b17c-37049ca3537d","duration_ms":25.901012,"app.r1":"REDACTED_R1","app.r2":"REDACTED_FIELD","response.status_code":"200","meta.instrumentations":["express","http","https"],"meta.instrumentation_count":3,"meta.beeline_version":"1.3.1","meta.node_version":"v11.6.0"} +0ms
```

## Source:

```
function foo(redactedField) {
    return new Promise((resolve, reject) => {
        const redactedKey = 'REDACTED_KEY';
        let span = _beeline.startSpan({
            task: 'foo',
            'redis.cmd': 'srem',
            'redis.key': redactedKey,
            'redis.field': redactedField
        });
        console.log(`TRACE ACTIVE? ${_beeline.traceActive()}`); // returns true
        _client.srem(redactedKey, redactedField, (err, reply) => {
            if (err) {
                _beeline.customContext.add("redis.err", err.toString());
                _beeline.finishSpan(span);
                reject(err);
            }
            else {
                _beeline.customContext.add("redis.reply", reply);
                _beeline.finishSpan(span);
                resolve(reply);
            }
        });
    });
}

async function onBar(redactedField) {
    return await foo(redactedField);
}

myExpressRouter.post('/redactedPath', middleware1, middleware2, middleware3, (req, res) => {
    const r1 = req.body.redactedField;
    const r2 = req.body.redactedField2;
    beeline.customContext.add('r1', r1);
    beeline.customContext.add('r2', r2);
    db.onBar(r1).then((barResult) => {
        res.json({ "REDACTED_PAYLOAD": true });
    }).catch((reason) => {
        res.json({ "REDACTED_PAYLOAD": false });
    });
});
```

**Comment by toshok** [comment]
Guessing this is due to the `redis` package needing some instrumentation just to make sure context is propagated through it.

Working around problems like this is one of the reasons that `bindFunctionToTrace` is part of the public API.

something like this will _probably_ fix it:

```
            _client.srem(redactedKey, redactedField, _beeline.bindFunctionToTrace((err, reply) => {
                if (err) {
                    _beeline.customContext.add("redis.err", err.toString());
                    _beeline.finishSpan(span);
                    reject(err);
                }
                else {
                    _beeline.customContext.add("redis.reply", reply);
                    _beeline.finishSpan(span);
                    resolve(reply);
                }
            }));
```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
