### ISSUE TITLE
stealthy-require breaks things

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#121]
currently comes up with `request-promise` usage.

Things break unless you manually require `https` / `http` before requiring `request-promise`

e.g.:

```
const beeline = require('honeycomb-beeline')({});

require('https'); // if I comment this out, I get an 'api.traceActive is not a function' error
const request = require('request-promise-native');

const trace = beeline.startTrace({
  task: 'http request',
});

beeline.startAsyncSpan({ name: "request"}, span => {
  return request({
    method: 'GET',
    url: 'https://www.google.com',
  }).then(() => {
    beeline.finishSpan(span);
  });
}).then(() => {
  beeline.finishTrace(trace);
});
```

**Comment by michaelpistrang-vetro** [comment]
I ran into this same `api.traceActive is not a function` error.  In my case it was with running a Node.js 10.X app managed by PM2 that connects to SQS (stack trace below). 

It turns out that PM2 was the issue.  I was running an older version of PM2, 2.X, and upgrading it to 4.X fixed this for me.

The solution above of manually adding the `require('https')` worked for me as well, however upgrading PM2 will be my long term fix in this case.

```
[ERROR] - { NetworkingError: api.traceActive is not a function
     at Object.request (/var/www/node_modules/honeycomb-beeline/lib/instrumentation/https.js:25:16)
     at features.constructor.handleRequest (/var/www/node_modules/aws-sdk/lib/http/node.js:42:23)
     at executeSend (/var/www/node_modules/aws-sdk/lib/event_listeners.js:304:29)
     at Request.SEND (/var/www/node_modules/aws-sdk/lib/event_listeners.js:318:9)
     at Request.callListeners (/var/www/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
     at Request.emit (/var/www/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
     at Request.emit (/var/www/node_modules/aws-sdk/lib/request.js:683:14)
     at Request.transition (/var/www/node_modules/aws-sdk/lib/request.js:22:10)
     at AcceptorStateMachine.runTo (/var/www/node_modules/aws-sdk/lib/state_machine.js:14:12)
     at /var/www/node_modules/aws-sdk/lib/state_machine.js:26:10
     at Request.<anonymous> (/var/www/node_modules/aws-sdk/lib/request.js:38:9)
     at Request.<anonymous> (/var/www/node_modules/aws-sdk/lib/request.js:685:12)
     at Request.callListeners (/var/www/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
     at callNextListener (/var/www/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
     at /var/www/node_modules/aws-sdk/lib/event_listeners.js:220:9
     at finish (/var/www/node_modules/aws-sdk/lib/config.js:320:7)
     at /var/www/node_modules/aws-sdk/lib/config.js:338:9
     at Credentials.get (/var/www/node_modules/aws-sdk/lib/credentials.js:126:7)
     at getAsyncCredentials (/var/www/node_modules/aws-sdk/lib/config.js:332:24)
     at Config.getCredentials (/var/www/node_modules/aws-sdk/lib/config.js:352:9)
     at Request.SIGN (/var/www/node_modules/aws-sdk/lib/event_listeners.js:192:22)
     at Request.callListeners (/var/www/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
message: 'api.traceActive is not a function',
code: 'NetworkingError',
... }
```

**Comment by michaelpistrang-vetro** [comment]
This bug also prevented the https library from being auto-instrumented, producing the following error.  The solution above continues to be a solid work around.

```
 honeycomb-beeline:event using impl: libhoney-event +0ms
  honeycomb-beeline:event using deterministic sampler with .sampleRate provided. +0ms
  honeycomb-beeline:instrumentation loading instrumentation for http@v10.23.0 +0ms
  honeycomb-beeline:instrumentation loading instrumentation for express@4.16.2 +98ms
  honeycomb-beeline:instrumentation loading instrumentation for child_process@v10.23.0 +211ms
  honeycomb-beeline:instrumentation loading instrumentation for pg@7.12.1 +172ms
  honeycomb-beeline:instrumentation loading instrumentation for bluebird@3.5.3 +363ms
  honeycomb-beeline:instrumentation loading instrumentation for https@v10.23.0 +50ms
  honeycomb-beeline:instrumentation loading instrumentation for https@v10.23.0 +83ms
  honeycomb-beeline:instrumentation failed to instrument modulehttps +0ms
  honeycomb-beeline:instrumentation TypeError: instrumentation is not a function
  honeycomb-beeline:instrumentation     at exports.instrumentLoad (/vagrant/www/node_modules/honeycomb-beeline/lib/instrumentation.js:112:15)
  honeycomb-beeline:instrumentation     at Function._load (/vagrant/www/node_modules/honeycomb-beeline/lib/instrumentation.js:165:16)
  honeycomb-beeline:instrumentation     at Module.require (internal/modules/cjs/loader.js:692:17)
  honeycomb-beeline:instrumentation     at require (internal/modules/cjs/helpers.js:25:18)
  honeycomb-beeline:instrumentation     at Object.<anonymous> (/vagrant/www/node_modules/form-data/lib/form_data.js:5:13)
  honeycomb-beeline:instrumentation     at Module._compile (internal/modules/cjs/loader.js:778:30)
  honeycomb-beeline:instrumentation     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  honeycomb-beeline:instrumentation     at Module.load (internal/modules/cjs/loader.js:653:32)
  honeycomb-beeline:instrumentation     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  honeycomb-beeline:instrumentation     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  honeycomb-beeline:instrumentation     at Function._load (/vagrant/www/node_modules/honeycomb-beeline/lib/instrumentation.js:164:28)
  honeycomb-beeline:instrumentation     at Module.require (internal/modules/cjs/loader.js:692:17)
  honeycomb-beeline:instrumentation     at require (internal/modules/cjs/helpers.js:25:18)
  honeycomb-beeline:instrumentation     at Object.<anonymous> (/vagrant/www/node_modules/superagent/lib/node/index.js:9:18)
  honeycomb-beeline:instrumentation     at Module._compile (internal/modules/cjs/loader.js:778:30)
  honeycomb-beeline:instrumentation     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  honeycomb-beeline:instrumentation     at Module.load (internal/modules/cjs/loader.js:653:32)
  honeycomb-beeline:instrumentation     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  honeycomb-beeline:instrumentation     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  honeycomb-beeline:instrumentation     at Function._load (/vagrant/www/node_modules/honeycomb-beeline/lib/instrumentation.js:164:28)
  honeycomb-beeline:instrumentation     at Module.require (internal/modules/cjs/loader.js:692:17)
```

While running on the versions below:

```
├── express-promise-router@2.0.0
├── express@4.16.2
├── honeycomb-beeline@2.6.0
└── request-promise@4.2.2
```
