### ISSUE TITLE
Stack trace from express

### ISSUE THREAD

**Issue by tgriesser** [honeycombio/beeline-nodejs#122]
Hey! First time trying honeycomb, really excited to get this working (if possible). Currently none of my express routes seem to be going through - this is the trace I'm getting for a request.

Tried implementing `bindFunctionToTrace` in a few places but no luck, are there certain patterns for what needs to be bound?

```
2019-02-21T22:52:39.055Z honeycomb-beeline:express -------------------
    honeycomb-beeline error: we lost our tracking somewhere in the stack handling ...
    Error
    at LibhoneyEventAPI.askForIssue ($PROJECT/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
    at Object._askForIssue ($PROJECT/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
    at api.bindFunctionToTrace ($PROJECT/node_modules/honeycomb-beeline/lib/instrumentation/express.js:214:11)
    at $PROJECT/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
    at ServerResponse.<anonymous> ($PROJECT/node_modules/honeycomb-beeline/lib/instrumentation/express.js:237:12)
    at ServerResponse.writeHead ($PROJECT/node_modules/on-headers/index.js:46:16)
    at ServerResponse.writeHead ($PROJECT/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead ($PROJECT/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:199:8)
    at ServerResponse.end ($PROJECT/node_modules/compression/index.js:103:14)
    at ServerResponse.send ($PROJECT/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json ($PROJECT/node_modules/express/lib/response.js:267:15)
    at ServerResponse.res.json ($PROJECT/packages/api/lib/routes/schema_version.js:128:12)
    at Index.Organization.getAllByUserWithCounts.then ($PROJECT/packages/api/lib/controllers/organizations.js:82:18)
    at $PROJECT/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
    at tryCatcher ($PROJECT/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback ($PROJECT/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback ($PROJECT/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback ($PROJECT/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback ($PROJECT/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback ($PROJECT/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler ($PROJECT/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill ($PROJECT/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve ($PROJECT/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled ($PROJECT/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise ($PROJECT/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 ($PROJECT/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($PROJECT/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($PROJECT/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($PROJECT/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($PROJECT/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($PROJECT/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
    current request context:
0: {"meta.type":"express","meta.package_version":"4.16.4","name":"request","request.host":"localhost","request.base_url":"","request.original_url":"/organizations","request.remote_addr":"::ffff:127.0.0.1","request.secure":false,"request.method":"GET","request.scheme":"http","request.path":"/organizations","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"36d57724-9f28-4d2c-b8d2-ed6a8e8ce1d8","trace.span_id":"5be5bebc-4cfc-4a78-9fd0-112829e4be72","startTime":1550789559033,"startTimeHR":[49403,205937840]}
    -------------------
```
On start:
```
honeycomb-beeline:event using impl: libhoney-event
honeycomb-beeline:instrumentation loading instrumentation for bluebird@3.5.3
honeycomb-beeline:instrumentation loading instrumentation for bluebird@2.11.0
honeycomb-beeline:instrumentation loading instrumentation for http@v10.13.0
honeycomb-beeline:instrumentation loading instrumentation for express@4.16.4
honeycomb-beeline:instrumentation loading instrumentation for https@v10.13.0
honeycomb-beeline:instrumentation loading instrumentation for child_process@v10.13.0
honeycomb-beeline:instrumentation loading instrumentation for bluebird@2.11.0
honeycomb-beeline:instrumentation loading instrumentation for bluebird@2.11.0
```

**Comment by tgriesser** [comment]
edit: misread the stack trace... taking a further look
