### ISSUE TITLE
__dirname usage results in failure when using webpack

### ISSUE THREAD

**Issue by mbravorus** [honeycombio/beeline-nodejs#128]
Hi,

I already heard from your support that your nodejs beeline doesn't seem to work with webpack; I'll file this issue in the hopes this might help fix it, maybe?

Do, the `__dirname` usage here:
https://github.com/honeycombio/beeline-nodejs/blob/432d8e52db33c3602a0650cca8b042f7a78d2a18/lib/api/index.js#L7

Bombs out when used with webpack, like this:

```
$ node dist/release.js
/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/Users/shvar/src/iqoqo-root/node_modules/honeycomb-beeline/lib sync:2
    var e = new Error("Cannot find module '" + req + "'");
^
Error: Cannot find module '/Users/shvar/src/iqoqo-root/packages/app-api-graphql/package.json'
    at webpackEmptyContext (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/Users/shvar/src/iqoqo-root/node_modules/honeycomb-beeline/lib sync:2:1)
    at Object.exports.log (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/Users/shvar/src/iqoqo-root/node_modules/honeycomb-beeline/lib/propagation.js:3:9)
    at __webpack_require__ (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/Users/shvar/src/iqoqo-root/node_modules/honeycomb-beeline/lib/api/index.js:5:17)
    at __webpack_require__ (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/Users/shvar/src/iqoqo-root/node_modules/honeycomb-beeline/lib/index.js:2:13)
    at __webpack_require__ (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/src/server.ts:1:1)
    at __webpack_require__ (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/shvar/src/iqoqo-root/packages/app-api-graphql/dist/webpack:/src/run.ts:4:1)

$ ls -l /Users/shvar/src/iqoqo-root/packages/app-api-graphql/package.json
-rw-r--r--  1 shvar  staff  4117 Mar 11 11:20 /Users/shvar/src/iqoqo-root/packages/app-api-graphql/package.json
```

This is after we have taken [this](https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92) into consideration and configured webpack with `node.__dirname = false`

Perhaps using `path.resolve("./")` instead of `__dirname` would have helped?

Please consider, I'm sure plenty of people using webpack for bundling would be delighted to use beelines. (it is also entirely possible that webpack integration has much more problems than this, we didn't go deeper)

**Comment by toshok** [comment]
going to track bundler support in #172, closing this bug.
