### ISSUE TITLE
Tracking lost leading to missing spans

### ISSUE THREAD

**Issue by ipanitchkov** [honeycombio/beeline-nodejs#138]
honeycomb-beeline error: we lost our tracking somewhere in the stack handling this request
    please paste this message (everything between the "----" lines) into an issue
    at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
    out any application stack frames if you'd rather not share those
    Error
    at LibhoneyEventAPI.askForIssue (PATH_TO_MY_PROJECT/node_modules/honeycomb-beeline/lib/api/libhoney.js:249:7)
    at Object._askForIssue (PATH_TO_MY_PROJECT/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
    at api.bindFunctionToTrace (PATH_TO_MY_PROJECT/node_modules/honeycomb-beeline/lib/instrumentation/express.js:214:11)
    at bindFunction (PATH_TO_MY_PROJECT/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19)
    at ServerResponse.<anonymous> (PATH_TO_MY_PROJECT/node_modules/honeycomb-beeline/lib/instrumentation/express.js:237:12)
    at ServerResponse.writeHead (PATH_TO_MY_PROJECT/node_modules/on-headers/index.js:35:16)
    at ServerResponse.writeHead (PATH_TO_MY_PROJECT/node_modules/on-headers/index.js:44:26)
    at ServerResponse.res.writeHead (PATH_TO_MY_PROJECT/node_modules/client-sessions/lib/client-sessions.js:627:24)
    at ServerResponse._implicitHeader (_http_server.js:200:8)
    at ServerResponse.end (_http_outgoing.js:712:10)
    at ServerResponse.send (PATH_TO_MY_PROJECT/node_modules/express/lib/response.js:221:10)
    at exports.apiReply (PATH_TO_MY_PROJECT/lib/httpUtils.ts:22:11)
    at clsBind (PATH_TO_MY_PROJECT/node_modules/cls-hooked/context.js:172:17)
    at clsBind (PATH_TO_MY_PROJECT/node_modules/cls-hooked/context.js:172:17)
    at tryCatcher (PATH_TO_MY_PROJECT/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (PATH_TO_MY_PROJECT/node_modules/bluebird/js/release/nodeify.js:22:30)
    current request context:
0: {"meta.type":"express","meta.package_version":"4.16.4","name":"request","request.host":"localhost","request.base_url":"","request.original_url":"/api/v1/config/test","request.remote_addr":"::1","request.secure":false,"request.method":"GET","request.scheme":"http","request.path":"/api/v1/config/test","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"f0bbdd5a-6559-421e-98ce-451b1121f927","trace.span_id":"febf2fae-2c2c-45e1-8613-d634905fa490","startTime":1556052468345,"startTimeHR":[113751,287059459]}

There is a **res.send(result);** on line 22 inside the **PATH_TO_MY_PROJECT/lib/httpUtils.ts** file if interested

**Comment by dsoo** [comment]
Hi, @ipanitchkov - I took a look at this - I unfortunately don't have quite enough knowledge of the beeline-nodejs codebase to know for certain what happened. The gist of this error message is that at some point we failed to propagate the context that we use. The most likely cause of this is a piece of middleware interfering with us managing our context, I think. What middleware are you using in your application?

@toshok, can you chime in? Any thoughts that you can add?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
