### ISSUE TITLE
Error when express.json() middleware first applied in application

### ISSUE THREAD

**Issue by allyjweir** [honeycombio/beeline-nodejs#148]
I am getting errors from beeline-nodejs when I have this as the first `app.use()` statement in my express application:
```app.use(express.json({ limit: '500kb' }));```
This is with express version 4.17.0.

The issue is oddly resolved by moving this declaration to be the second `app.use()` statement.

Here is the output from beeline-nodejs:
```
  honeycomb-beeline:express -------------------
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the middleware registered:
  honeycomb-beeline:express     at Function.<anonymous> (/Users/aweir/workspace/clever-rostering-service/node_modules/express/lib/application.js:220:21)
  honeycomb-beeline:express     at Array.forEach (<anonymous>)
  honeycomb-beeline:express     at Function.use (/Users/aweir/workspace/clever-rostering-service/node_modules/express/lib/application.js:217:7)
  honeycomb-beeline:express     at Object.exports.default (/Users/aweir/workspace/clever-rostering-service/src/application.ts:34:9)
  honeycomb-beeline:express     at Object.<anonymous> (/Users/aweir/workspace/clever-rostering-service/src/server.ts:11:24)
  honeycomb-beeline:express     at Module._compile (internal/modules/cjs/loader.js:701:30)
  honeycomb-beeline:express     at Module.m._compile (/Users/aweir/workspace/clever-rostering-service/node_modules/ts-node/src/index.ts:439:23)
  honeycomb-beeline:express     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
  honeycomb-beeline:express     at Object.require.extensions.(anonymous function) [as .ts] (/Users/aweir/workspace/clever-rostering-service/node_modules/ts-node/src/index.ts:442:12)
  honeycomb-beeline:express     at Module.load (internal/modules/cjs/loader.js:600:32)
  honeycomb-beeline:express     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error: 
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/api/libhoney.js:282:7)
  honeycomb-beeline:express     at Object._askForIssue (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
  honeycomb-beeline:express     at wrappedNext (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/instrumentation/express.js:125:15)
  honeycomb-beeline:express     at /Users/aweir/workspace/clever-rostering-service/node_modules/body-parser/lib/read.js:130:5
  honeycomb-beeline:express     at invokeCallback (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:224:16)
  honeycomb-beeline:express     at done (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:213:7)
  honeycomb-beeline:express     at IncomingMessage.onEnd (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:273:7)
  honeycomb-beeline:express     at IncomingMessage.emit (events.js:194:15)
  honeycomb-beeline:express     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
  honeycomb-beeline:express     at endReadableNT (_stream_readable.js:1125:12)
  honeycomb-beeline:express     at process._tickCallback (internal/process/next_tick.js:63:19)
  honeycomb-beeline:express     
  honeycomb-beeline:express     -------------------
```

Happily modified my application to avoid this error, placing the call to `express.json()` to be the second invocation of `app.use()` but hoped reporting would still be helpful. If I can provide any more information, please let me know.

**Comment by allyjweir** [comment]
Had another instance of this error in a different service which could not be remedied by moving the invocation of `express.json()`.

```
  honeycomb-beeline:express -------------------
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the middleware registered:
  honeycomb-beeline:express     at Function.<anonymous> (/Users/aweir/workspace/clever-rostering-service/node_modules/express/lib/application.js:220:21)
  honeycomb-beeline:express     at Array.forEach (<anonymous>)
  honeycomb-beeline:express     at Function.use (/Users/aweir/workspace/clever-rostering-service/node_modules/express/lib/application.js:217:7)
  honeycomb-beeline:express     at Object.exports.default (/Users/aweir/workspace/clever-rostering-service/src/application.ts:34:9)
  honeycomb-beeline:express     at Object.<anonymous> (/Users/aweir/workspace/clever-rostering-service/src/server.ts:11:24)
  honeycomb-beeline:express     at Module._compile (internal/modules/cjs/loader.js:701:30)
  honeycomb-beeline:express     at Module.m._compile (/Users/aweir/workspace/clever-rostering-service/node_modules/ts-node/src/index.ts:439:23)
  honeycomb-beeline:express     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
  honeycomb-beeline:express     at Object.require.extensions.(anonymous function) [as .ts] (/Users/aweir/workspace/clever-rostering-service/node_modules/ts-node/src/index.ts:442:12)
  honeycomb-beeline:express     at Module.load (internal/modules/cjs/loader.js:600:32)
  honeycomb-beeline:express     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error: 
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/api/libhoney.js:282:7)
  honeycomb-beeline:express     at Object._askForIssue (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
  honeycomb-beeline:express     at wrappedNext (/Users/aweir/workspace/clever-rostering-service/node_modules/honeycomb-beeline/lib/instrumentation/express.js:125:15)
  honeycomb-beeline:express     at /Users/aweir/workspace/clever-rostering-service/node_modules/body-parser/lib/read.js:130:5
  honeycomb-beeline:express     at invokeCallback (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:224:16)
  honeycomb-beeline:express     at done (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:213:7)
  honeycomb-beeline:express     at IncomingMessage.onEnd (/Users/aweir/workspace/clever-rostering-service/node_modules/raw-body/index.js:273:7)
  honeycomb-beeline:express     at IncomingMessage.emit (events.js:194:15)
  honeycomb-beeline:express     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
  honeycomb-beeline:express     at endReadableNT (_stream_readable.js:1125:12)
  honeycomb-beeline:express     at process._tickCallback (internal/process/next_tick.js:63:19)
  honeycomb-beeline:express     
  honeycomb-beeline:express     ------------------- +0ms
```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
