### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by twpol** [honeycombio/beeline-nodejs#157]
I encountered this issue with the MongoDB instrumentation but only with certain connection strings. It isn't clear to me what the difference is but:

* Works: mongodb://user:pass@host1,host2,host3/database?replicaSet=rsname
* Breaks: mongodb://user:pass@host1,host2,host3/database?ssl=true&replicaSet=rsname&authSource=admin&retryWrites=true

The error below is generated from a `debug(…)` line, but if I comment that out it will still fail to send the event for the same reason:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at tracker.runWithoutTracking (...\node_modules\honeycomb-beeline\lib\api\libhoney.js:256:53)
    at AsyncTracker.runWithoutTracking (...\node_modules\honeycomb-beeline\lib\async_tracker.js:29:14)
    at LibhoneyEventAPI.finishSpan (...\node_modules\honeycomb-beeline\lib\api\libhoney.js:204:13)
    at Object.finishSpan (...\node_modules\honeycomb-beeline\lib\api\index.js:67:20)
    at ...\node_modules\honeycomb-beeline\lib\instrumentation\mongodb.js:62:21
    at ...\node_modules\honeycomb-beeline\lib\async_tracker.js:47:19
    at err (...\node_modules\mongoose\node_modules\mongodb\lib\utils.js:415:14)
    at session.endSession (...\node_modules\mongoose\node_modules\mongodb\lib\utils.js:399:27)
    at ClientSession.endSession (...\node_modules\mongoose\node_modules\mongodb-core\lib\sessions.js:129:41)
    at executeCallback (...\node_modules\mongoose\node_modules\mongodb\lib\utils.js:397:17)
    at executeOperation (...\node_modules\mongoose\node_modules\mongodb\lib\utils.js:422:7)
    at Collection.<anonymous> (...\node_modules\mongoose\node_modules\mongodb\lib\collection.js:1028:12)
    at Collection.deprecated (...\node_modules\mongoose\node_modules\mongodb\lib\utils.js:669:15)
    at api.startAsyncSpan.span (...\node_modules\honeycomb-beeline\lib\instrumentation\mongodb.js:66:31)
    at tracker.callWithContext (...\node_modules\honeycomb-beeline\lib\api\libhoney.js:163:42)
```

**Comment by aphix** [comment]
Also getting same thing immediately upon 1st request which requires a db connection. Just started a trial, so only initial require w/ default configuration is being used.

**Comment by ekumahost** [comment]
you did not include your code, but I think a resource that return a promise is what you are converting to json instead of doing .then().catch()

**Comment by aphix** [comment]
Ah, it's awaitable/es7 but perhaps a an await here would make the difference; will give it a shot tomorrow if the trial is still running, thanks.

`enabledInstrumentations: await (beeline
	.getInstrumentations())
	...`

**Comment by twpol** [comment]
I have diagnosed my issue further, and found that in some cases we get an `options.session` passed into the MongoDB call (and thus the instrumentation) which contains a `ClientSession` object. This is not something that is suitable for converting to JSON.
