### ISSUE TITLE
Running more than one node-pg query with callback syntax with mock impl raises error

### ISSUE THREAD

**Issue by allyjweir** [honeycombio/beeline-nodejs#159]
In my testing of my PR related to #37, I am finding that queries to postgres using node-postgres' callback syntax fails after more than one query is made when Honeycomb is using the mock implementation.

The error returned is as follows: 
```
➜  pg-trace-example git:(master) ✗ yarn start
yarn run v1.17.3
warning ../../package.json: No license field
$ nodemon
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/allyjweir/workspace/pg-trace-example/src/**/*
[nodemon] starting `ts-node -r dotenv/config src/server.ts`
  honeycomb-initialiser Starting honeycomb +0ms
2019-08-09T09:04:55.294Z [info]: Server running at port 8080 on PID: 82364
::1 - - [09/Aug/2019:09:04:57 +0000] "GET /example/callback/text-only HTTP/1.1" 200 62 "-" "-"

/Users/allyjweir/workspace/pg-trace-example/node_modules/honeycomb-beeline/lib/api/index.js:133
    return apiImpl.askForIssue(msg, logger);
                   ^
TypeError: apiImpl.askForIssue is not a function
    at Object._askForIssue (/Users/allyjweir/workspace/pg-trace-example/node_modules/honeycomb-beeline/lib/api/index.js:133:20)
    at api.bindFunctionToTrace (/Users/allyjweir/workspace/pg-trace-example/node_modules/honeycomb-beeline/lib/instrumentation/express.js:214:11
)
    at /Users/allyjweir/workspace/pg-trace-example/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
    at ServerResponse.<anonymous> (/Users/allyjweir/workspace/pg-trace-example/node_modules/honeycomb-beeline/lib/instrumentation/express.js:237
:12)
    at ServerResponse.writeHead (/Users/allyjweir/workspace/pg-trace-example/node_modules/on-headers/index.js:35:16)
    at ServerResponse.writeHead (/Users/allyjweir/workspace/pg-trace-example/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:181:8)
    at write_ (_http_outgoing.js:635:9)
    at ServerResponse.end (_http_outgoing.js:754:5)
    at ServerResponse.send (/Users/allyjweir/workspace/pg-trace-example/node_modules/express/lib/response.js:221:10)
```

I verified this behaviour does not occur for either promises or async-await.

For a minimal reproduction,

1. Clone this repo, follow setup in README _without_ linking to local version of beeline: https://github.com/allyjweir/pg-trace-example
2. Start server locally using `yarn start`
3. Run in terminal: `curl localhost:8080/callback/text-only` twice.

It should error on the second call of curl.

**Comment by carterbancroft** [comment]
I'm running into this issue as well with some express instrumentation using the mock. I'm researching it but also if anyone has any idea what the correct fix would be maybe it'd be something I could submit a PR for.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
