### ISSUE TITLE
[express] Tracking lost when a previous middleware perform an external call using callbacks

### ISSUE THREAD

**Issue by dario1985** [honeycombio/beeline-nodejs#177]
### Description

I detected that when some previous middleware performs some external calls (eg. using `request` library) without using promises the context is lost and traces are not correctly reported.

This happen for example using auth0's `jwks-rsa` integration library for dinamically fetch and verify JWT secrets.

### Error trace
```
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the middleware registered:
  honeycomb-beeline:express     at Function.<anonymous> (/home/dario/Workspace/honeycomb-express-issue/node_modules/express/lib/application.js:220:21)
  honeycomb-beeline:express     at Array.forEach (<anonymous>)
  honeycomb-beeline:express     at Function.use (/home/dario/Workspace/honeycomb-express-issue/node_modules/express/lib/application.js:217:7)
  honeycomb-beeline:express     at Object.<anonymous> (/home/dario/Workspace/honeycomb-express-issue/index.js:12:5)
  honeycomb-beeline:express     at Module._compile (internal/modules/cjs/loader.js:959:30)
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/home/dario/Workspace/honeycomb-express-issue/node_modules/honeycomb-beeline/lib/api/libhoney.js:295:7)
  honeycomb-beeline:express     at Object._askForIssue (/home/dario/Workspace/honeycomb-express-issue/node_modules/honeycomb-beeline/lib/api/index.js:137:20)
  honeycomb-beeline:express     at wrappedNext (/home/dario/Workspace/honeycomb-express-issue/node_modules/honeycomb-beeline/lib/instrumentation/express.js:35:15)
  honeycomb-beeline:express     at Request._callback (/home/dario/Workspace/honeycomb-express-issue/index.js:13:34)
  honeycomb-beeline:express     at Request.self.callback (/home/dario/Workspace/honeycomb-express-issue/node_modules/request/request.js:185:22)
  honeycomb-beeline:express     at Request.emit (events.js:210:5)
  honeycomb-beeline:express     at Request.<anonymous> (/home/dario/Workspace/honeycomb-express-issue/node_modules/request/request.js:1161:10)
  honeycomb-beeline:express     at Request.emit (events.js:210:5)
  honeycomb-beeline:express     at IncomingMessage.<anonymous> (/home/dario/Workspace/honeycomb-express-issue/node_modules/request/request.js:1083:12)
  honeycomb-beeline:express     at Object.onceWrapper (events.js:299:28)
```

### Steps to reproduce:
```javascript
const beeline = require('honeycomb-beeline')();
const express = require('express');
const http = require('http');

const port = process.env.PORT || 3001;
const app = express();

const request = require('request');
const url = 'https://jsonplaceholder.typicode.com/todos/1';

// ISSUE HAPPEN: External call Middleware using callback
app.use((req, res, next) => {
  request(url, (e, res, body) => next(null, null));
});

// ISSUE DOESN'T HAPPEN: Wrapping external call using promises (with then)
/*app.use((req, res, next) => {
  new Promise(done => request(url, (e, res, body) => done()))
    .then(() => next(null, null));
});*/

// ISSUE DOESN'T HAPPEN: Wrapping external call using promises (with async/await)
/*app.use(async (req, res, next) => {
  await new Promise(done => request(url, (e, res, body) => done()));
  next(null, null);
});*/

// ISSUE DOESN'T HAPPEN: Trying to reproduce just with simple callback with setImmediate/setTimeout/nextTick
/*app.use((req, res, next) => {
  setImmediate(() => next(null, null));
});*/

// Main Controller
app.get('/', (req, res) => {
  res.json({ message: 'hello world!' });
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

**Comment by toshok** [comment]
make sense.  we'll probably need to write a `request` instrumentation to get it to propagate our async context.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
