### ISSUE TITLE
no context in startSpan/finishSpan

### ISSUE THREAD

**Issue by janpio** [honeycombio/beeline-nodejs#211]
I have only rudimentary understanding of JS, so please bear with me:

I am using [Prisma Client](https://github.com/prisma/prisma) to make a database request. Internally, Prisma Client uses a binary to do the actual queries. Right now I only have a span around the whole Prisma Client call, but I identified `prisma.fetcher.request` as the function that executes the binary - so a span around the function would give me insight how long the binary execution takes vs. the whole of Prisma Client.

So I was trying to monkey patch that function, but I get this output unfortunately:

```
  honeycomb-beeline:event -------------------
  honeycomb-beeline:event     honeycomb-beeline error: no context in startSpan.
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:event     out any application stack frames if you'd rather not share those
  honeycomb-beeline:event     Error
  honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\libhoney.js:322:7)
  honeycomb-beeline:event     at LibhoneyEventAPI.startSpan (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\libhoney.js:114:12)
  honeycomb-beeline:event     at Function.startSpan (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\index.js:74:20)
  honeycomb-beeline:event     at PrismaClientFetcher.<anonymous> (C:\Users\Jan\Documents\prisma-chinook-express\src\index.js:68:26)
  honeycomb-beeline:event     at Object.then (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\@prisma\client\runtime\index.js:1:146249)
  honeycomb-beeline:event
  honeycomb-beeline:event     ------------------- +0ms
  honeycomb-beeline:event finishing span undefined +2s
  honeycomb-beeline:event -------------------
  honeycomb-beeline:event     honeycomb-beeline error: no context in finishSpan.
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:event     out any application stack frames if you'd rather not share those
  honeycomb-beeline:event     Error
  honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\libhoney.js:322:7)
  honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\libhoney.js:183:12)
  honeycomb-beeline:event     at Function.finishSpan (C:\Users\Jan\Documents\prisma-chinook-express\node_modules\honeycomb-beeline\lib\api\index.js:77:20)
  honeycomb-beeline:event     at PrismaClientFetcher.<anonymous> (C:\Users\Jan\Documents\prisma-chinook-express\src\index.js:70:15)
  honeycomb-beeline:event     at processTicksAndRejections (internal/process/task_queues.js:85:5)
  honeycomb-beeline:event
  honeycomb-beeline:event     ------------------- +1ms
```

This is how my monkey patching attempt looks like:

```js
if(useHoneycomb) {
  var shimmer = require('shimmer');

  shimmer.wrap(prisma.fetcher, 'request', function (original) {
    return async function (...args) {
      var span = beeline.startSpan('prisma.fetcher.request')
      let results = await original.apply(this, args)
      beeline.finishSpan(span)
      return results
    };
  });
  
}
```

Is that even the correct approach?
How can I make the necessary context available?

PS: https://github.com/honeycombio/beeline-nodejs/issues/120 sounds related, but I do not understand what it means really :/

**Comment by janpio** [comment]
I had a similar problem with Elastic APM when playing with their node client any my bad monkey patching tries, but could it there by putting the `transaction` (which includes a context) into a global var and then use that one instead of the main object - but my `beeline_copy` from a working `startSpan` did not make a difference here unfortunately :/

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
