### ISSUE TITLE
Error: we lost our tracking somewhere in the middleware registered

### ISSUE THREAD

**Issue by andrewoh531** [honeycombio/beeline-nodejs#239]
I'm seeing the following in our logs with debug enabled. We are using [q](https://github.com/kriskowal/q) in parts of our application and I came across this [issue around passthrough for q](https://github.com/honeycombio/beeline-nodejs/issues/36). Does this mean that Q is interfering with the async context propagation?

I'd like to confirm this before adding a task to replace Q with native Promises.

```
  honeycomb-beeline:express -------------------
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the middleware registered:
  honeycomb-beeline:express     at Function.<anonymous> (/Users/andrewoh/Projects/my-app/my-app/node_modules/express/lib/application.js:220:21)
  honeycomb-beeline:express     at Array.forEach (<anonymous>)
  honeycomb-beeline:express     at Function.use (/Users/andrewoh/Projects/my-app/my-app/node_modules/express/lib/application.js:217:7)
  honeycomb-beeline:express     at module.exports (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Configuration/Express/Express.ts:231:7)
  honeycomb-beeline:express     at Injector.invoke (/Users/andrewoh/Projects/my-app/my-app/node_modules/hxroin/heroin.js:119:17)
  honeycomb-beeline:express     at Injector.localGet (/Users/andrewoh/Projects/my-app/my-app/node_modules/hxroin/heroin.js:314:42)
  honeycomb-beeline:express     at Injector.get (/Users/andrewoh/Projects/my-app/my-app/node_modules/hxroin/heroin.js:100:21)
  honeycomb-beeline:express     at Object.default (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/InitApp.ts:9:6)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:19:17
  honeycomb-beeline:express     at step (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:33:23)
  honeycomb-beeline:express     at Object.next (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:14:53)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:8:71
  honeycomb-beeline:express     at new Promise (<anonymous>)
  honeycomb-beeline:express     at __awaiter (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:4:12)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/Bootstrapper/Bootstrapper.ts:4:52
  honeycomb-beeline:express     at Injector.invoke (/Users/andrewoh/Projects/my-app/my-app/node_modules/hxroin/heroin.js:119:17)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:14:12
  honeycomb-beeline:express     at step (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:33:23)
  honeycomb-beeline:express     at Object.next (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:14:53)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:8:71
  honeycomb-beeline:express     at new Promise (<anonymous>)
  honeycomb-beeline:express     at __awaiter (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:4:12)
  honeycomb-beeline:express     at Object.default (/Users/andrewoh/Projects/my-app/my-app/Server/Source/Server.ts:6:43)
  honeycomb-beeline:express     at Object.<anonymous> (/Users/andrewoh/Projects/my-app/my-app/Server/Boot.js:14:11)
  honeycomb-beeline:express     at Module._compile (internal/modules/cjs/loader.js:1138:30)
  honeycomb-beeline:express     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  honeycomb-beeline:express     at Module.load (internal/modules/cjs/loader.js:986:32)
  honeycomb-beeline:express     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  honeycomb-beeline:express     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  honeycomb-beeline:express     at internal/main/run_main_module.js:17:47
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error:
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/Users/andrewoh/Projects/my-app/my-app/node_modules/honeycomb-beeline/lib/api/libhoney.js:345:7)
  honeycomb-beeline:express     at Object._askForIssue (/Users/andrewoh/Projects/my-app/my-app/node_modules/honeycomb-beeline/lib/api/index.js:196:20)
  honeycomb-beeline:express     at wrappedNext (/Users/andrewoh/Projects/my-app/my-app/node_modules/honeycomb-beeline/lib/instrumentation/express.js:35:15)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/Server/Source/Common/XssFilter/XssFilter.coffee:131:18
  honeycomb-beeline:express     at clsBind (/Users/andrewoh/Projects/my-app/my-app/node_modules/cls-hooked/context.js:172:17)
  honeycomb-beeline:express     at _fulfilled (/Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:854:54)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:883:30
  honeycomb-beeline:express     at Promise.promise.promiseDispatch (/Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:816:13)
  honeycomb-beeline:express     at /Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:877:14
  honeycomb-beeline:express     at runSingle (/Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:137:13)
  honeycomb-beeline:express     at flush (/Users/andrewoh/Projects/my-app/my-app/node_modules/q/q.js:125:13)
  honeycomb-beeline:express     at processTicksAndRejections (internal/process/task_queues.js:79:11)
  honeycomb-beeline:express
  honeycomb-beeline:express     ------------------- +10m
```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
