### ISSUE TITLE
error: no payload for span we're trying to finish (span not found)

### ISSUE THREAD

**Issue by patelvarun** [honeycombio/beeline-nodejs#307]
```
  honeycomb-beeline:event -------------------
  honeycomb-beeline:event honeycomb-beeline error: no payload for span we're trying to finish (span not found).
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:event     out any application stack frames if you'd rather not share those
  honeycomb-beeline:event     Error
  honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (/Users/projects/node_modules/honeycomb-beeline/lib/api/libhoney.js:344:7)
  honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (/Users/projects/node_modules/honeycomb-beeline/lib/api/libhoney.js:216:12)
  honeycomb-beeline:event     at Function.finishSpan (/Users/projects/node_modules/honeycomb-beeline/lib/api/index.js:116:20)
  honeycomb-beeline:event     at TapSubscriber._tapNext (/Users/projects/dist/logger/logger.interceptor.js:71:27)
  honeycomb-beeline:event     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  honeycomb-beeline:event     current request context:
  honeycomb-beeline:event 0: {"payload":{"meta.type":"express","meta.package_version":"4.17.1","name":"request","request.host":"localhost","request.original_url":"/wowe/api/v1/users","request.remote_addr":"::1","request.secure":false,"request.method":"GET","request.scheme":"http","request.path":"/wowe/api/v1/users","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"request.header.user_agent":"PostmanRuntime/7.26.8","request.header.accept":"*/*","trace.trace_id":"f3c84dea877f2452084d0893802313b4","trace.span_id":"14b2dff48109fc4a","response":"{\"users\":[],\"totalUsers\":0}","task_ms":34.253251},"startTime":1612802165078,"startTimeHR":[48591,770106919]}
  honeycomb-beeline:event     ------------------- +1ms
step 2---
```

**Comment by vreynolds** [comment]
Thanks for submitting the issue @patelvarun! Did you notice if this happens in particular cases, e.g. when using `startAsyncSpan`?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
