### ISSUE TITLE
Not able to parse sendlib requests

### ISSUE THREAD

**Issue by kanolato** [honeycombio/beeline-nodejs#329]
Hey there! recently we started to add some custom context to some of our requests however, they never make it to honeycomb, after enabling the debug mode for beeline we found this:
```  honeycomb-beeline:express -------------------
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the stack handling this request
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/app/node_modules/honeycomb-beeline/lib/api/libhoney.js:344:7)
  honeycomb-beeline:express     at Object._askForIssue (/app/node_modules/honeycomb-beeline/lib/api/index.js:207:20)
  honeycomb-beeline:express     at /app/node_modules/honeycomb-beeline/lib/instrumentation/express.js:145:11
  honeycomb-beeline:express     at /app/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
  honeycomb-beeline:express     at ServerResponse.<anonymous> (/app/node_modules/honeycomb-beeline/lib/instrumentation/express.js:174:12)
  honeycomb-beeline:express     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:35:16)
  honeycomb-beeline:express     at ServerResponse._implicitHeader (_http_server.js:246:8)
  honeycomb-beeline:express     at write_ (_http_outgoing.js:685:9)
  honeycomb-beeline:express     at ServerResponse.end (_http_outgoing.js:799:5)
  honeycomb-beeline:express     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
  honeycomb-beeline:express     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
  honeycomb-beeline:express     at /app/packages/jb4c-api/src/restApp.js:29:28
  honeycomb-beeline:express     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  honeycomb-beeline:express     current request context:
  honeycomb-beeline:express 0: {"payload":{"meta.type":"express","meta.package_version":"4.17.1","name":"request","trace.trace_id_source":"X-Request-ID http header","request.host":"xxxx.xxxx.com","request.original_url":"/hooks/XXXX","request.remote_addr":"::ffff:10.28.2.220","request.secure":false,"request.method":"POST","request.scheme":"http","request.path":"/hooks/XXXX","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"request.header.x_forwarded_for":"10.26.2.50","request.header.x_forwarded_proto":"https","request.header.x_forwarded_port":"443","request.header.user_agent":"Sendlib/1.0","request.header.content_type":"multipart/form-data; boundary=xYzZY","trace.trace_id":"1097e86ac1c2de31ae89dcf5a4b1c836","trace.span_id":"bfc00ee39b950e53"},"startTime":1617042338844,"startTimeHR":[27033833,23492403]}
  honeycomb-beeline:express     ------------------- +0ms
  ```
  Happy to help with any further details.
  We are using:
  - Node 14
  - honeycomb-beeline 2.6.0
  - express 4.17.1
  - multer 1.4.2
All of our other endpoints work well, the only difference we have in this one is that we are using multer as a middleware, maybe that could be the cause

**Comment by vreynolds** [comment]
Thank you for letting us know! We’ll investigate as soon as we can. 🕵🏽‍♀️

**Comment by vreynolds** [comment]
Unfortunately, there's not a smoking gun in the stack trace. I tried a sample app with your versions, and I'm not seeing the same issue, but I think your suspicion of the `multer` is a good one. Can you share a trimmed/sanitized example app that has the issue?

**Comment by vreynolds** [comment]
We're going to close this, since there hasn't been any activity for a while. Feel free to comment with additional information, and we'll be glad to re-open.
